# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(30, 60, 731, 81))
        self.columnView.setObjectName("columnView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 111, 17))
        self.label.setObjectName("label")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(380, 340, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(
            QtCore.QRect(40, 100, 711, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.batCount = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.batCount.setFont(font)
        self.batCount.setStyleSheet("color: rgb(21, 203, 223);")
        self.batCount.setObjectName("batCount")
        self.horizontalLayout_2.addWidget(self.batCount)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.bowCount = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bowCount.setFont(font)
        self.bowCount.setStyleSheet("color: rgb(21, 203, 223);")
        self.bowCount.setObjectName("bowCount")
        self.horizontalLayout_2.addWidget(self.bowCount)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.arCount = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.arCount.setFont(font)
        self.arCount.setStyleSheet("color: rgb(21, 203, 223);")
        self.arCount.setObjectName("arCount")
        self.horizontalLayout_2.addWidget(self.arCount)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.wkCount = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wkCount.setFont(font)
        self.wkCount.setStyleSheet("color: rgb(21, 203, 223);")
        self.wkCount.setObjectName("wkCount")
        self.horizontalLayout_2.addWidget(self.wkCount)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 170, 281, 361))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.avPoints = QtWidgets.QLabel(self.groupBox)
        self.avPoints.setGeometry(QtCore.QRect(120, 0, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.avPoints.setFont(font)
        self.avPoints.setStyleSheet("color: rgb(21, 203, 223);")
        self.avPoints.setObjectName("avPoints")
        self.listWidget_nonSlPlayers = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_nonSlPlayers.setGeometry(
            QtCore.QRect(70, 70, 141, 281))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.listWidget_nonSlPlayers.setFont(font)
        self.listWidget_nonSlPlayers.setStyleSheet("color : rgb(21, 203, 223)")
        self.listWidget_nonSlPlayers.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget_nonSlPlayers.setLineWidth(1)
        self.listWidget_nonSlPlayers.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget_nonSlPlayers.setObjectName("listWidget_nonSlPlayers")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 251, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_bat = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_bat.setObjectName("radio_bat")
        self.horizontalLayout.addWidget(self.radio_bat)
        self.radio_bow = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_bow.setObjectName("radio_bow")
        self.horizontalLayout.addWidget(self.radio_bow)
        self.radio_ar = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_ar.setObjectName("radio_ar")
        self.horizontalLayout.addWidget(self.radio_ar)
        self.radio_wk = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_wk.setObjectName("radio_wk")
        self.horizontalLayout.addWidget(self.radio_wk)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 170, 271, 361))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.usedPoints = QtWidgets.QLabel(self.groupBox_2)
        self.usedPoints.setGeometry(QtCore.QRect(100, 0, 41, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usedPoints.setFont(font)
        self.usedPoints.setStyleSheet("color: rgb(21, 203, 223);")
        self.usedPoints.setObjectName("usedPoints")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(
            QtCore.QRect(10, 30, 251, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.team_name = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.team_name.setFont(font)
        self.team_name.setStyleSheet("color: rgb(21, 203, 223);")
        self.team_name.setObjectName("team_name")
        self.horizontalLayout_5.addWidget(self.team_name)
        self.listWidget_slPlayers = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_slPlayers.setGeometry(QtCore.QRect(60, 70, 141, 281))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.listWidget_slPlayers.setFont(font)
        self.listWidget_slPlayers.setStyleSheet("color: rgb(21, 203, 223);")
        self.listWidget_slPlayers.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget_slPlayers.setLineWidth(1)
        self.listWidget_slPlayers.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget_slPlayers.setObjectName("listWidget_slPlayers")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuManage_Team = QtWidgets.QMenu(self.menubar)
        self.menuManage_Team.setObjectName("menuManage_Team")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_TEam = QtWidgets.QAction(MainWindow)
        self.actionOPEN_TEam.setObjectName("actionOPEN_TEam")
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        self.actionEVALUTE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUTE_Team.setObjectName("actionEVALUTE_Team")
        self.menuManage_Team.addAction(self.actionNEW_Team)
        self.menuManage_Team.addAction(self.actionOPEN_TEam)
        self.menuManage_Team.addAction(self.actionSAVE_Team)
        self.menuManage_Team.addAction(self.actionEVALUTE_Team)
        self.menubar.addAction(self.menuManage_Team.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FantasyCricket"))
        self.label.setText(_translate("MainWindow", "Your Selections"))
        self.label_13.setText(_translate("MainWindow", ">"))
        self.label_2.setText(_translate("MainWindow", "Batsmen (BAT)  "))
        self.batCount.setText(_translate("MainWindow", "##"))
        self.label_3.setText(_translate("MainWindow", "Bowlers (BOW)  "))
        self.bowCount.setText(_translate("MainWindow", "##"))
        self.label_4.setText(_translate("MainWindow", "Allrounders (AR) "))
        self.arCount.setText(_translate("MainWindow", "##"))
        self.label_5.setText(_translate("MainWindow", "Wicket-Keepers (WK)"))
        self.wkCount.setText(_translate("MainWindow", "##"))
        self.groupBox.setTitle(_translate("MainWindow", "Points Available"))
        self.avPoints.setText(_translate("MainWindow", "####"))
        self.radio_bat.setText(_translate("MainWindow", "BAT"))
        self.radio_bow.setText(_translate("MainWindow", "BWL"))
        self.radio_ar.setText(_translate("MainWindow", "AR"))
        self.radio_wk.setText(_translate("MainWindow", "WK"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Points Used"))
        self.usedPoints.setText(_translate("MainWindow", "####"))
        self.label_8.setText(_translate("MainWindow", "Team Name"))
        self.team_name.setText(_translate("MainWindow", "Displayed Here"))
        self.menuManage_Team.setTitle(_translate("MainWindow", "Manage Team"))
        self.actionNEW_Team.setText(_translate("MainWindow", "&NEW Team"))
        self.actionNEW_Team.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOPEN_TEam.setText(_translate("MainWindow", "&OPEN Team"))
        self.actionOPEN_TEam.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "&SAVE Team"))
        self.actionSAVE_Team.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionEVALUTE_Team.setText(
            _translate("MainWindow", "&EVALUTE Team"))
        self.actionEVALUTE_Team.setShortcut(_translate("MainWindow", "Ctrl+E"))
